# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-27 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docresults',
            name='doc_full_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docresults',
            name='doc_meta_exif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
