# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170727_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='docresults',
            name='doc_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
